# Generated by Django 4.2.6 on 2023-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='handled_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='party_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=1, help_text='Priority on a scale of 1 to 10', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Qualified', 'Qualified'), ('On Progress', 'On Progress'), ('Done', 'Done'), ('Decline', 'Decline')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='website',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
