# Generated by Django 5.0.7 on 2024-07-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
