# Generated by Django 5.0.7 on 2024-07-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_db_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
    ]
